# Generated by Django 6.0.5 on 2026-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_amount',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
